### PR TITLE
Fix read_data for multi-node, add masses

### LINKED ISSUE #11: Read masses from data file
Not a high priority, but worth supporting in the same way lammps does

### PR DESCRIPTION
**Pull request by streeve**
The previous version only worked with one MPI rank and did not handle masses or potential coefficients (still ignored, but not an error).

Closes #11

### CODE REVIEW

**Review by saakethdesai — APPROVED** [review]

File: src/read_data.h [hunk 1]
```diff
@@ -213,88 +218,123 @@ void read_lammps_atoms( ifstream &file, System *s )
             }
             // getline pushed to the end of loop because line already stores the
             // 1st non-blank line after exiting while loop
-            getline( file, line );
+            std::getline( file, line );
         }
     }
     s->N_local = counter;
-    s->N = counter;
```
Comment (streeve) [inline src/read_data.h:220]: This is the line that broke multi-rank runs
